name: feature-workflow

on: 
  push:
    branches: 
      - feature/*
    
env: 
    AZURE_RESOURCEGROUP_NAME: ToyWebsiteTest
    ENVIRONMENT_TYPE: Test

jobs:
  lint: 
     uses: vermegi/biceplearnGHPRs/.github/workflows/lint.yml@main

  createRG: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    
      - name: get resource group name
        id: rgName
        run: |
         echo "github ref_name: ${{ github.refname }}"
         featurebranch=${{ github.refname }}
         feature=${$featurebranch:19}
         echo "feature: $feature"
         rgname=rg_f_$feature
         echo $rgname
         echo "::set-output name=rgname::$rgname"  
      - uses: Azure/cli@v1
        name: Create resource group
        with: 
          inlineScript: az group create -n ${{rgName.outputs.rgname}} -l westeurope
