name: pr-validation

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    
jobs:
  my-status-check: 
     uses: vermegi/biceplearnGHPRs/.github/workflows/lint.yml@main

  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/login@v1
        name: Sign in to Azure
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}    
      - name: create resource group name
        id: rgName
        run: |
         echo "github ref_name: ${{ github.ref }}"
         IFS='/' read -ra my_array <<< "${{ github.ref }}"
         export rgname=rg_f_${my_array[3]}
         echo "::set-output name=rgname::$rgname"  
      - uses: Azure/cli@v1
        name: Create resource group
        with: 
          inlineScript: az group create -n ${{steps.rgName.outputs.rgname}} -l westeurope
      - uses: azure/arm-deploy@v1
        id: deploy
        name: Deploy Bicep file
        with:
          failOnStdErr: false
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ steps.rgName.outputs.rgname }}
          template: ./deploy/main.bicep
          parameters: >
            environmentType=nonprod

