name: featuretest-workflow

on: 
  pull_request:
    
env: 
    AZURE_RESOURCEGROUP_NAME: ToyWebsiteTest
    ENVIRONMENT_TYPE: Test

jobs:
  lint: 
     runs-on: ubuntu-latest
     steps: 
     - uses: actions/checkout@v2
     - name: Run Bicep linter
       run: az bicep build --file deploy/main.bicep
  
  testGHBranchName:
    runs-on: ubuntu-latest
    steps:
      - name: GHoutputs
        run: |
          echo "-----------------------------"
          echo "full object: ${{ github }}"
          echo "-----------------------------"
          echo "github head_ref: ${{ github.head_ref }}" 
          echo "github base_ref: ${{ github.base_ref }}"
          echo "github ref: ${{ github.ref }}"
          echo "github ref_name: ${{ github.ref_name }}"
          echo "on push to feature branch:"
          echo "  github.head_ref:"
          echo "  github.base_ref:"
          echo "  github.ref: refs/heads/feature/123"
          echo "on pr open: "
          echo "  github.head_ref: feature/123"
          echo "  github.base_ref: main"
          echo "  github.ref: refs/pull/3/merge"
          echo "on pr edit: "
          echo "  github.head_ref:"
          echo "  github.base_ref:"
          echo "  github.ref: refs/heads/feature/123"
          echo "on pr close: "
          echo "  github.head_ref: feature/123"
          echo "  github.base_ref: main"
          echo "  github.ref: main"
  
  # validate: 
  #    runs-on: ubuntu-latest
  #    steps: 
  #    - uses: actions/checkout@v2
  #    - uses: azure/login@v1
  #      name: Sign in to Azure
  #      with:
  #        creds: ${{ secrets.AZURE_CREDENTIALS }}    
  #    - uses: azure/arm-deploy@v1
  #      name: Run preflight validation
  #      with:
  #        deploymentName: ${{ github.run_number }}
  #        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
  #        template: ./deploy/main.bicep
  #        parameters: environmentType=${{ env.ENVIRONMENT_TYPE }}
  #        deploymentMode: Validate
        
  # preview:
  #    runs-on: ubuntu-latest
  #    needs: [lint, validate]
  #    steps: 
  #    - uses: actions/checkout@v2
  #    - uses: azure/login@v1
  #      name: Sign in to Azure
  #      with:
  #        creds: ${{ secrets.AZURE_CREDENTIALS }}    
  #    - uses: Azure/cli@v1
  #      name: Run what-if
  #      with:
  #        inlineScript: |
  #            az deployment group what-if \
  #              --resource-group ${{ env.AZURE_RESOURCEGROUP_NAME }} \
  #              --template-file deploy/main.bicep \
  #              --parameters environmentType=${{ env.ENVIRONMENT_TYPE }}
 
